### PR TITLE
Create py.typed

### LINKED ISSUE #21: Please include `py.typed` marker file per PEP 561
https://www.python.org/dev/peps/pep-0561/#packaging-type-information

> Package maintainers who wish to support type checking of their code MUST add a marker file named py.typed to their package supporting typing.

Without this, projects using `gpiod` will fail to run mypy if `ignore_missing_imports = False`

```
gpio.py:7:1: error: Skipping analyzing "gpiod": found module but no type hints or library stubs  [import]
```

### PR DESCRIPTION
**Pull request by uSpike**
Fixes #21

### CODE REVIEW

**Comment by uSpike** [comment]
I'm not sure if this package needs to also specify `package_data` in setup.cfg.

**Comment by hhk7734** [comment]
I've never used mypy, so I don't know what the problem is.
But I will add this because it does not affect the whole package.

**Comment by ghost** [comment]
Hi, any chance you could publish a new release with this merged? I'm currently manually injecting this file in our test venvs for mypy to pick up but having this distributed with the package would be a huge quality of live improvement :).

**Comment by ghost** [comment]
Unfortunately I don't think the `py.typed` file actually made it into the resulting package. I don't know off-hand how to fix that though either :-/.

**Comment by uSpike** [comment]
Dangit!  setuptools `package_data` is only used for binary distributions??

```
$ python setup.py bdist
...
copying py_src/gpiod/py.typed -> build/lib/gpiod
```
UGH

**Pull request merged**
